all: OwnTracks-29.png \
	OwnTracks-darkmode-29.png 
#	OwnTracksCTRL-29.png \
#	OwnTracksRecorder-29.png \
#	OwnTracksActivo-29.png \
#	OwnTracksActivo-Outline-29.png \
#	pista-micro-29.png

OwnTracks-29.png:OwnTracks.svg
	./resize.sh OwnTracks.svg

OwnTracks-darkmode-29.png:OwnTracks-darkmode.svg
	./resize.sh OwnTracks-darkmode.svg

OwnTracksCTRL-29.png:OwnTracksCTRL.svg
	./resize.sh OwnTracksCTRL.svg

OwnTracksActivo-29.png:OwnTracksActivo.svg
	./resize.sh OwnTracksActivo.svg

OwnTracksRecorder-29.png:OwnTracksRecorder.svg
	./resize.sh OwnTracksRecorder.svg

OwnTracksActivo-Outline-29.png:OwnTracksActivo-Outline.svg
	./resize.sh OwnTracksActivo-Outline.svg

pista-micro-29.png:pista-micro.svg
	./resize.sh pista-micro.svg
