all: OwnTracks-29.png OwnTracksActivo-29.png OwnTracksActivo-Outline-29.png pista-micro-29.png

OwnTracks-29.png:OwnTracks.svg
	./resize.sh OwnTracks.svg

OwnTracksActivo-29.png:OwnTracksActivo.svg
	./resize.sh OwnTracksActivo.svg

OwnTracksActivo-Outline-29.png:OwnTracksActivo-Outline.svg
	./resize.sh OwnTracksActivo-Outline.svg

pista-micro-29.png:pista-micro.svg
	./resize.sh pista-micro.svg
